# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updash < Formula
  desc "System Update Dashboard — one binary for package updates, AI tools, and smart cleanup"
  homepage "https://github.com/lgldsilva/updash"
  version "0.15.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgldsilva/updash/releases/download/v0.15.1/updash_0.15.1_darwin_amd64.tar.gz"
      sha256 "fcbc20118f6af8120210441160caa10f1271edb0baa87952748889267c4a9540"

      def install
        bin.install "updash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgldsilva/updash/releases/download/v0.15.1/updash_0.15.1_darwin_arm64.tar.gz"
      sha256 "4511e347d95f4c70c236b612809050d968434c43b4ba51db884f1402406b9740"

      def install
        bin.install "updash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgldsilva/updash/releases/download/v0.15.1/updash_0.15.1_linux_amd64.tar.gz"
      sha256 "517821a2cf67b1344e2e0837e0b274c01260323fe04942d96ad35e5de80cd3dd"
      def install
        bin.install "updash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgldsilva/updash/releases/download/v0.15.1/updash_0.15.1_linux_arm64.tar.gz"
      sha256 "1150b6972842fa459ce29022204ded080c591afb846c8fab4529256ec695c4f9"
      def install
        bin.install "updash"
      end
    end
  end

  test do
    system "#{bin}/updash", "--version"
  end
end
